package(default_visibility = ["//visibility:public"])

java_test(
    name = "HttpPrivacyBudgetClientTest",
    srcs = ["HttpPrivacyBudgetClientTest.java"],
    deps = [
        "//java/com/google/scp/coordinator/privacy/budgeting/model",
        "//java/com/google/scp/operator/cpio/privacybudgetclient",
        "//java/com/google/scp/shared/api/exception",
        "//java/com/google/scp/shared/api/model",
        "//java/com/google/scp/shared/mapper",
        "//java/external:acai",
        "//java/external:apache_httpclient",
        "//java/external:apache_httpcore",
        "//java/external:google_truth",
        "//java/external:guice",
        "//java/external:jackson_databind",
        "//java/external:mockito",
    ],
)
