package(default_visibility = ["//visibility:public"])

java_library(
    name = "kmstoolenclave",
    srcs = [
        "KmsToolEnclaveAead.java",
    ],
    deps = [
        "//java/com/google/scp/shared/aws/credsprovider",
        "//java/external:aws_auth",
        "//java/external:aws_regions",
        "//java/external:guava",
        "//java/external:tink",
    ],
)
