package(default_visibility = ["//visibility:public"])

java_library(
    name = "awskmsv2",
    srcs = glob(["*.java"]),
    deps = [
        "//java/external:aws_auth",
        "//java/external:aws_core",
        "//java/external:aws_http_client_spi",
        "//java/external:aws_kms",
        "//java/external:aws_profiles",
        "//java/external:aws_regions",
        "//java/external:aws_utils",
        "//java/external:guava",
        "//java/external:tink",
    ],
)
