package(default_visibility = ["//visibility:public"])

java_library(
    name = "common",
    srcs = glob(["*.java"]),
    deps = [
        "//java/external:acai",
        "//java/external:bazel_runfiles",
        "//java/external:google_truth",
        "//java/external:guava",
        "//java/external:guice",
        "//java/external:junit",
        "//java/external:resilience4j_core",
        "//java/external:resilience4j_retry",
    ],
)
