package(default_visibility = ["//visibility:public"])

java_library(
    name = "model",
    srcs = glob(["*.java"]),
    deps = [
        "//java/external:autovalue",
        "//java/external:autovalue_annotations",
    ],
)
