package(default_visibility = ["//visibility:public"])

java_test(
    name = "TimeObjectMapperTest",
    srcs = ["TimeObjectMapperTest.java"],
    deps = [
        "//java/com/google/scp/operator/frontend/testing",
        "//java/com/google/scp/shared/api/model",
        "//java/com/google/scp/shared/mapper",
        "//java/external:google_truth",
        "//java/external:jackson_core",
        "//java/external:protobuf_java",
        "//java/external:protobuf_java_util",
        "//shared/protos/api/v1:java_proto",
    ],
)
