package(default_visibility = ["//cc:scp_internal_pkg"])

cc_library(
    name = "lib_cpio_mock",
    srcs = ["mock_lib_cpio.h"],
    deps = [
        "//cc:cc_base_include_dir",
        "//cc/cpio/client_providers/global_cpio/mock:global_cpio_mock",
        "//cc/cpio/client_providers/global_cpio/src:global_cpio_lib",
    ],
)
