package(default_visibility = ["//visibility:public"])

java_library(
    name = "model",
    srcs = glob(["*.java"]),
    deps = [
        "//java/com/google/scp/operator/shared/model",
        "//java/external:autovalue",
        "//java/external:autovalue_annotations",
        "//java/external:jackson_annotations",
        "//operator/protos/shared/backend:java_proto",
    ],
)
