package(default_visibility = ["//visibility:public"])

java_library(
    name = "attributeconverter",
    srcs = glob(["*.java"]),
    deps = [
        "//java/com/google/scp/operator/shared/model",
        "//java/external:aws_dynamodb",
        "//java/external:aws_dynamodb_enhanced",
        "//java/external:guava",
        "//operator/protos/shared/backend:java_proto",
    ],
)
