package(default_visibility = ["//cc:scp_internal_pkg"])

exports_files([
    "metric_client.cc",
    "metric_client.h",
])

filegroup(
    name = "metric_client_srcs",
    srcs = [
        ":metric_client.cc",
        ":metric_client.h",
    ],
)
