package(default_visibility = ["//visibility:public"])

java_test(
    name = "ObjectMapperSerializerTest",
    srcs = ["ObjectMapperSerializerTest.java"],
    deps = [
        "//java/com/google/scp/operator/frontend/serialization",
        "//java/com/google/scp/operator/frontend/testing",
        "//java/com/google/scp/shared/mapper",
        "//java/external:acai",
        "//java/external:google_truth",
        "//java/external:google_truth8",
        "//java/external:guava",
        "//java/external:guice",
        "//java/external:jackson_annotations",
        "//java/external:jackson_core",
        "//java/external:jackson_databind",
    ],
)
