package(default_visibility = ["//visibility:public"])

java_library(
    name = "credsprovider",
    srcs = glob(["*.java"]),
    deps = [
        "//java/external:aws_auth",
        "//java/external:aws_regions",
        "//java/external:aws_sts",
        "//java/external:guava",
    ],
)
