package(default_visibility = ["//visibility:public"])

java_library(
    name = "testing",
    srcs = ["ServiceExceptionAssertions.java"],
    deps = [
        "//java/com/google/scp/shared/api/exception",
        "//java/external:google_truth",
    ],
)
