package(default_visibility = ["//cc:scp_internal_pkg"])

exports_files([
    "config_client.cc",
    "config_client.h",
    "error_codes.h",
])

filegroup(
    name = "config_client_srcs",
    srcs = [
        ":config_client.cc",
        ":config_client.h",
        ":error_codes.h",
    ],
)
