load("@rules_pkg//:mappings.bzl", "pkg_files")

package(default_visibility = ["//visibility:public"])

# Collection of all docs to be included in the all-inclusive release package.
pkg_files(
    name = "docs",
    srcs = [
        "README.md",
    ],
)
