java_test(
    name = "ErrorCountsAttributeConverterTest",
    srcs = ["ErrorCountsAttributeConverterTest.java"],
    deps = [
        "//java/com/google/scp/operator/shared/dao/metadatadb/aws/model/attributeconverter",
        "//java/com/google/scp/operator/shared/model",
        "//java/external:aws_dynamodb",
        "//java/external:aws_dynamodb_enhanced",
        "//java/external:google_truth",
        "//operator/protos/shared/backend:java_proto",
    ],
)
