package(default_visibility = ["//visibility:public"])

java_library(
    name = "proto",
    srcs = glob(["*.java"]),
    deps = [
        "//java/external:guava",
        "//java/external:protobuf_java",
    ],
)
