/*
 * Copyright 2022 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.google.scp.operator.shared.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.google.auto.value.AutoValue;
import java.time.Instant;

/** Object for result data generated by the worker during processing. */
@JsonDeserialize(builder = ResultInfo.Builder.class)
@JsonSerialize(as = ResultInfo.class)
@Deprecated
@AutoValue
abstract class ResultInfo {

  /** String representing an empty result location. */
  public static final String EMPTY_RESULT_LOCATION = "/";

  /** Creates a new instance of the builder for this class. */
  public static Builder builder() {
    return Builder.builder();
  }

  /** Creates a {@link Builder} with values copied over. Used for creating an updated object. */
  public abstract Builder toBuilder();

  /** Return code for the aggregation job. */
  @JsonProperty("return_code")
  public abstract String returnCode();

  /** Return message for the aggregation job. */
  @JsonProperty("return_message")
  public abstract String returnMessage();

  /** Summary of partial failures in aggregation. */
  @JsonProperty("error_summary")
  public abstract ErrorSummary errorSummary();

  /** Timestamp of the aggregation request completion. */
  @JsonProperty("finished_at")
  public abstract Instant finishedAt();

  /** Builder class for the {@code ResultInfo} class. */
  @AutoValue.Builder
  public abstract static class Builder {

    /** Returns a new instance of the builder for the {@code ResultInfo} class. */
    @JsonCreator
    public static Builder builder() {
      return new AutoValue_ResultInfo.Builder();
    }

    /** Set the return code for the aggregation job. */
    @JsonProperty("return_code")
    public abstract Builder setReturnCode(String value);

    /** Set the return message for the aggregation job. */
    @JsonProperty("return_message")
    public abstract Builder setReturnMessage(String value);

    /** Set the summary of partial failures in aggregation. */
    @JsonProperty("error_summary")
    public abstract Builder setErrorSummary(ErrorSummary value);

    /** Set the timestamp of the aggregation request completion. */
    @JsonProperty("finished_at")
    public abstract Builder setFinishedAt(Instant value);

    /** Returns a new instance of the {@code ResultInfo} class from the builder. */
    public abstract ResultInfo build();
  }
}
