package(default_visibility = ["//visibility:public"])

java_library(
    name = "exception",
    srcs = glob(["*.java"]),
    deps = [
        "//java/com/google/scp/shared/api/model",
        "//java/external:guava",
    ],
)
