package(default_visibility = ["//visibility:public"])

java_test(
    name = "GetJobResponseConverterTest",
    srcs = [
        "GetJobResponseConverterTest.java",
    ],
    deps = [
        "//java/com/google/scp/operator/frontend/injection/modules/testing:fake_frontend_module",
        "//java/com/google/scp/operator/frontend/service/converter",
        "//java/com/google/scp/operator/frontend/service/model",
        "//java/com/google/scp/operator/shared/dao/metadatadb/testing:job_generator",
        "//java/com/google/scp/operator/shared/model",
        "//java/com/google/scp/shared/api/model",
        "//java/external:acai",
        "//java/external:google_truth",
        "//java/external:google_truth8",
        "//java/external:guice",
        "//javatests/com/google/scp/operator/frontend/service",
        "//javatests/com/google/scp/shared/testutils/common",
        "//operator/protos/frontend/api/v1:java_proto",
        "//operator/protos/shared/backend/metadatadb:java_proto",
    ],
)

java_test(
    name = "CreateJobRequestToRequestInfoConverterTest",
    srcs = [
        "CreateJobRequestToRequestInfoConverterTest.java",
    ],
    deps = [
        "//java/com/google/scp/operator/frontend/service/converter",
        "//java/com/google/scp/operator/frontend/service/model",
        "//java/com/google/scp/operator/shared/dao/metadatadb/testing:job_generator",
        "//java/com/google/scp/operator/shared/model",
        "//java/com/google/scp/shared/api/model",
        "//java/external:acai",
        "//java/external:google_truth",
        "//java/external:google_truth8",
        "//java/external:guice",
        "//javatests/com/google/scp/operator/frontend/service",
        "//operator/protos/frontend/api/v1:java_proto",
        "//operator/protos/shared/backend:java_proto",
    ],
)

java_test(
    name = "ResultInfoConverterTest",
    srcs = [
        "ResultInfoConverterTest.java",
    ],
    deps = [
        "//java/com/google/scp/operator/frontend/injection/modules/testing:fake_frontend_module",
        "//java/com/google/scp/operator/frontend/service/converter",
        "//java/com/google/scp/operator/frontend/service/model",
        "//java/com/google/scp/operator/shared/dao/metadatadb/testing:job_generator",
        "//java/com/google/scp/operator/shared/model",
        "//java/com/google/scp/shared/api/model",
        "//java/external:acai",
        "//java/external:google_truth",
        "//java/external:google_truth8",
        "//java/external:guice",
        "//javatests/com/google/scp/operator/frontend/service",
        "//javatests/com/google/scp/shared/testutils/common",
        "//operator/protos/frontend/api/v1:java_proto",
        "//operator/protos/shared/backend:java_proto",
    ],
)

java_test(
    name = "ErrorSummaryConverterTest",
    srcs = [
        "ErrorSummaryConverterTest.java",
    ],
    deps = [
        "//java/com/google/scp/operator/frontend/injection/modules/testing:fake_frontend_module",
        "//java/com/google/scp/operator/frontend/service/converter",
        "//java/com/google/scp/operator/frontend/service/model",
        "//java/com/google/scp/operator/shared/dao/metadatadb/testing:job_generator",
        "//java/com/google/scp/operator/shared/model",
        "//java/com/google/scp/shared/api/model",
        "//java/external:acai",
        "//java/external:google_truth",
        "//java/external:google_truth8",
        "//java/external:guice",
        "//javatests/com/google/scp/operator/frontend/service",
        "//javatests/com/google/scp/shared/testutils/common",
        "//operator/protos/frontend/api/v1:java_proto",
        "//operator/protos/shared/backend:java_proto",
    ],
)

java_test(
    name = "JobStatusConverterTest",
    srcs = [
        "JobStatusConverterTest.java",
    ],
    deps = [
        "//java/com/google/scp/operator/frontend/service/converter",
        "//java/com/google/scp/operator/frontend/service/model",
        "//java/com/google/scp/operator/shared/model",
        "//java/external:acai",
        "//java/external:google_truth",
        "//java/external:google_truth8",
        "//java/external:guice",
        "//javatests/com/google/scp/operator/frontend/service",
        "//operator/protos/frontend/api/v1:java_proto",
        "//operator/protos/shared/backend:java_proto",
    ],
)

java_test(
    name = "ErrorCountConverterTest",
    srcs = [
        "ErrorCountConverterTest.java",
    ],
    deps = [
        "//java/com/google/scp/operator/frontend/injection/modules/testing:fake_frontend_module",
        "//java/com/google/scp/operator/frontend/service/converter",
        "//java/com/google/scp/operator/frontend/service/model",
        "//java/com/google/scp/operator/shared/dao/metadatadb/testing:job_generator",
        "//java/com/google/scp/operator/shared/model",
        "//java/com/google/scp/shared/api/model",
        "//java/external:acai",
        "//java/external:google_truth",
        "//java/external:google_truth8",
        "//java/external:guice",
        "//javatests/com/google/scp/operator/frontend/service",
        "//javatests/com/google/scp/shared/testutils/common",
        "//operator/protos/frontend/api/v1:java_proto",
        "//operator/protos/shared/backend:java_proto",
    ],
)
