package(default_visibility = ["//visibility:public"])

java_library(
    name = "factories",
    srcs = glob(["*.java"]),
    deps = [
        "//java/external:guava",
        "//java/external:guice",
    ],
)
