package(default_visibility = ["//visibility:public"])

java_test(
    name = "LocalFileDecryptionKeyServiceTest",
    srcs = ["LocalFileDecryptionKeyServiceTest.java"],
    deps = [
        "//java/com/google/scp/operator/cpio/cryptoclient:aws",
        "//java/external:acai",
        "//java/external:google_truth",
        "//java/external:guice",
        "//java/external:jimfs",
        "//java/external:tink",
    ],
)
