package(default_visibility = ["//visibility:public"])

java_library(
    name = "util",
    srcs = glob(["*.java"]),
    deps = [
        "//java/com/google/scp/shared/api/exception",
        "//java/com/google/scp/shared/api/model",
        "//java/external:jackson_core",
        "//java/external:jackson_databind",
        "//java/external:protobuf_java",
        "//java/external:protobuf_java_util",
        "//shared/protos/api/v1:java_proto",
    ],
)
