package(default_visibility = ["//visibility:public"])

java_library(
    name = "serialization",
    srcs = glob(["*.java"]),
    deps = [
        "//java/external:guava",
        "//java/external:guice",
        "//java/external:jackson_core",
        "//java/external:jackson_databind",
        "//java/external:protobuf_java",
        "//java/external:protobuf_java_util",
    ],
)
