package(default_visibility = ["//visibility:public"])

java_test(
    name = "FakeRequestInfoValidatorTest",
    srcs = ["FakeRequestInfoValidatorTest.java"],
    deps = [
        "//java/com/google/scp/operator/frontend/testing:fake_request_info_validator",
        "//java/com/google/scp/operator/shared/model",
        "//java/external:google_truth",
        "//java/external:google_truth8",
        "//java/external:guava",
        "//operator/protos/shared/backend:java_proto",
    ],
)
