package(default_visibility = ["//visibility:public"])

java_library(
    name = "common",
    srcs = glob(["*.java"]),
    deps = [
        "//java/external:guice",
        "//operator/protos/shared/backend/asginstance:java_proto",
        "//operator/protos/shared/backend/metadatadb:java_proto",
    ],
)
