package(default_visibility = ["//visibility:public"])

java_test(
    name = "FSBlobStorageClientTest",
    srcs = ["FSBlobStorageClientTest.java"],
    deps = [
        "//java/com/google/scp/operator/cpio/blobstorageclient",
        "//java/external:acai",
        "//java/external:google_truth",
        "//java/external:google_truth8",
        "//java/external:guice",
        "//java/external:jimfs",
    ],
)
